//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Petty.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Petty.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string ButtonApply {
            get {
                return ResourceManager.GetString("ButtonApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a coffee, I&apos;m tired :(.
        /// </summary>
        internal static string ButtonBuyCoffee {
            get {
                return ResourceManager.GetString("ButtonBuyCoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ButtonClear {
            get {
                return ResourceManager.GetString("ButtonClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ButtonDefault {
            get {
                return ResourceManager.GetString("ButtonDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I read all messages personally :).
        /// </summary>
        internal static string ButtonDonate {
            get {
                return ResourceManager.GetString("ButtonDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string ButtonDownload {
            get {
                return ResourceManager.GetString("ButtonDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string ButtonLater {
            get {
                return ResourceManager.GetString("ButtonLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak.
        /// </summary>
        internal static string ButtonSpeak {
            get {
                return ResourceManager.GetString("ButtonSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop.
        /// </summary>
        internal static string ButtonStartStop {
            get {
                return ResourceManager.GetString("ButtonStartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to call.
        /// </summary>
        internal static string CommandCall {
            get {
                return ResourceManager.GetString("CommandCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flashlight.
        /// </summary>
        internal static string CommandFlashlight {
            get {
                return ResourceManager.GetString("CommandFlashlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to petty.
        /// </summary>
        internal static string CommandPetName {
            get {
                return ResourceManager.GetString("CommandPetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screenshot.
        /// </summary>
        internal static string CommandScreenshot {
            get {
                return ResourceManager.GetString("CommandScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello leather bag, how are you?.
        /// </summary>
        internal static string EditorVoiceTestSpeech {
            get {
                return ResourceManager.GetString("EditorVoiceTestSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current language:.
        /// </summary>
        internal static string LabelSettingsCurrentLanguage {
            get {
                return ResourceManager.GetString("LabelSettingsCurrentLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        internal static string LabelSettingsPitch {
            get {
                return ResourceManager.GetString("LabelSettingsPitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value: {0}.
        /// </summary>
        internal static string LabelSettingsValue {
            get {
                return ResourceManager.GetString("LabelSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string LabelSettingsVolume {
            get {
                return ResourceManager.GetString("LabelSettingsVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string LanguageRussian {
            get {
                return ResourceManager.GetString("LanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string PageAbout {
            get {
                return ResourceManager.GetString("PageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base settings.
        /// </summary>
        internal static string PageBaseSettings {
            get {
                return ResourceManager.GetString("PageBaseSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        internal static string PageDiagnostics {
            get {
                return ResourceManager.GetString("PageDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string PageHelp {
            get {
                return ResourceManager.GetString("PageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        internal static string PageLeaderboard {
            get {
                return ResourceManager.GetString("PageLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petty.
        /// </summary>
        internal static string PagePetty {
            get {
                return ResourceManager.GetString("PagePetty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageSettings {
            get {
                return ResourceManager.GetString("PageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulator speech.
        /// </summary>
        internal static string PageSpeechSimulator {
            get {
                return ResourceManager.GetString("PageSpeechSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string PageVoiceSettings {
            get {
                return ResourceManager.GetString("PageVoiceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bracket.
        /// </summary>
        internal static string SpeechCommandBracket {
            get {
                return ResourceManager.GetString("SpeechCommandBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сolon.
        /// </summary>
        internal static string SpeechCommandColon {
            get {
                return ResourceManager.GetString("SpeechCommandColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сomma.
        /// </summary>
        internal static string SpeechCommandComma {
            get {
                return ResourceManager.GetString("SpeechCommandComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exclamation mark.
        /// </summary>
        internal static string SpeechCommandExclamationMark {
            get {
                return ResourceManager.GetString("SpeechCommandExclamationMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new line.
        /// </summary>
        internal static string SpeechCommandNewLine {
            get {
                return ResourceManager.GetString("SpeechCommandNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        internal static string SpeechCommandPoint {
            get {
                return ResourceManager.GetString("SpeechCommandPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question mark.
        /// </summary>
        internal static string SpeechCommandQuestionMark {
            get {
                return ResourceManager.GetString("SpeechCommandQuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote.
        /// </summary>
        internal static string SpeechCommandQuote {
            get {
                return ResourceManager.GetString("SpeechCommandQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        internal static string TitleCommands {
            get {
                return ResourceManager.GetString("TitleCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string TitleDownloading {
            get {
                return ResourceManager.GetString("TitleDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words for punctuation marks:.
        /// </summary>
        internal static string TitlePunctuationWords {
            get {
                return ResourceManager.GetString("TitlePunctuationWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful features:.
        /// </summary>
        internal static string UsefulFeatures {
            get {
                return ResourceManager.GetString("UsefulFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your network connection and try again..
        /// </summary>
        internal static string UserMessageCheckNetworkConnection {
            get {
                return ResourceManager.GetString("UserMessageCheckNetworkConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command is not supported on this device..
        /// </summary>
        internal static string UserMessageCommandNotSupported {
            get {
                return ResourceManager.GetString("UserMessageCommandNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not found..
        /// </summary>
        internal static string UserMessageContactNotFound {
            get {
                return ResourceManager.GetString("UserMessageContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable Petty&apos;s protection?.
        /// </summary>
        internal static string UserMessageDisablePettyGuard {
            get {
                return ResourceManager.GetString("UserMessageDisablePettyGuard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading in progress, please wait for it to complete..
        /// </summary>
        internal static string UserMessageDownloadingInProgress {
            get {
                return ResourceManager.GetString("UserMessageDownloadingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For start voice recognizing you need to download a voice model (about 128 MB).
        /// </summary>
        internal static string UserMessageDownloadVoskModelMessage {
            get {
                return ResourceManager.GetString("UserMessageDownloadVoskModelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People don&apos;t understand what you say, but do you think your speech is normal? 
        ///There is a solution!!! 
        ///Petty speech simulator will help you in this difficult task. 
        ///Just start talking and it will show you what people hear.
        ///Your speech will be here, good luck!).
        /// </summary>
        internal static string UserMessagePettySpeechSimulatorPlaceholder {
            get {
                return ResourceManager.GetString("UserMessagePettySpeechSimulatorPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.S. This button starts and stops Petty&apos;s voice assistant throughout the application..
        /// </summary>
        internal static string UserMessagePettyStartStopRemark {
            get {
                return ResourceManager.GetString("UserMessagePettyStartStopRemark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation is already in progress. Please try again later..
        /// </summary>
        internal static string UserMessageTryLater {
            get {
                return ResourceManager.GetString("UserMessageTryLater", resourceCulture);
            }
        }
    }
}
