// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PettySQLite;

#nullable disable

namespace PettySQLite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("PettySQLite.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LanguageType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lol")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Slider3Value")
                        .HasColumnType("REAL");

                    b.Property<bool?>("TryHarder")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("TryInverted")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("UseFrontCamera")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
